<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>CrmApp.Domain</RootNamespace>
    <AssemblyName>CrmApp.Domain</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR.Contracts" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Constants\" />
  </ItemGroup>

</Project>
