<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

  <ItemGroup>
    <ProjectReference Include="..\Web\Web.csproj" />
    <ProjectReference Include="..\Shared\Shared.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>592181f7-48b3-449b-a796-2f3a3e9905c9</UserSecretsId>
  </PropertyGroup>

</Project>
